<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<SignAssembly>false</SignAssembly>
		<IncludeSymbols>true</IncludeSymbols>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Version>0.0.2</Version>
		<Authors>dududu</Authors>
		<RepositoryUrl>https://github.com/weianweigan/PMPageControl.git</RepositoryUrl>
		<PackageProjectUrl>https://github.com/weianweigan/PMPageControl</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<EnableComHosting>true</EnableComHosting>
		<Description>Create SolidWorks PMPage with xaml</Description>
		<PackageIcon>pmpageicon.png</PackageIcon>
		<AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
		<XcadRegDll>false</XcadRegDll>
		<NoWarn>CS1591</NoWarn>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Assets\Images\pmpageicon.png" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Xarial.XCad.SolidWorks" Version="0.8.3" />
	</ItemGroup>

	<ItemGroup>
		<None Include="solidworks-init.ps1" pack="true" PackagePath="tools\init.ps1" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\Images\pmpageicon.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
</Project>