<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<!--<XCadRegDll>false</XCadRegDll>-->
		<OutputType>Library</OutputType>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<EnableComHosting>true</EnableComHosting>
		<LangVersion>latest</LangVersion>
		<!--<XCadRegDll>false</XCadRegDll>-->
	</PropertyGroup>
	
	<ItemGroup>
		<!--<PackageReference Include="Du.PMPage.Wpf" Version="0.0.1" />-->
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\Du.PMPage.Wpf\Du.PMPage.Wpf.csproj" />
	</ItemGroup>

</Project>